// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: metaMessage.proto

package de.velcommuta.denul.networking.protobuf.meta;

public final class MetaMessage {
  private MetaMessage() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
  }
  public interface WrapperOrBuilder extends
      // @@protoc_insertion_point(interface_extends:de.velcommuta.denul.networking.protobuf.meta.Wrapper)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>optional .de.velcommuta.denul.networking.protobuf.c2s.ClientHello ClientHello = 1;</code>
     */
    boolean hasClientHello();
    /**
     * <code>optional .de.velcommuta.denul.networking.protobuf.c2s.ClientHello ClientHello = 1;</code>
     */
    de.velcommuta.denul.networking.protobuf.c2s.C2S.ClientHello getClientHello();
    /**
     * <code>optional .de.velcommuta.denul.networking.protobuf.c2s.ClientHello ClientHello = 1;</code>
     */
    de.velcommuta.denul.networking.protobuf.c2s.C2S.ClientHelloOrBuilder getClientHelloOrBuilder();

    /**
     * <code>optional .de.velcommuta.denul.networking.protobuf.c2s.ServerHello ServerHello = 2;</code>
     */
    boolean hasServerHello();
    /**
     * <code>optional .de.velcommuta.denul.networking.protobuf.c2s.ServerHello ServerHello = 2;</code>
     */
    de.velcommuta.denul.networking.protobuf.c2s.C2S.ServerHello getServerHello();
    /**
     * <code>optional .de.velcommuta.denul.networking.protobuf.c2s.ServerHello ServerHello = 2;</code>
     */
    de.velcommuta.denul.networking.protobuf.c2s.C2S.ServerHelloOrBuilder getServerHelloOrBuilder();

    /**
     * <code>optional .de.velcommuta.denul.networking.protobuf.c2s.Store Store = 3;</code>
     */
    boolean hasStore();
    /**
     * <code>optional .de.velcommuta.denul.networking.protobuf.c2s.Store Store = 3;</code>
     */
    de.velcommuta.denul.networking.protobuf.c2s.C2S.Store getStore();
    /**
     * <code>optional .de.velcommuta.denul.networking.protobuf.c2s.Store Store = 3;</code>
     */
    de.velcommuta.denul.networking.protobuf.c2s.C2S.StoreOrBuilder getStoreOrBuilder();

    /**
     * <code>optional .de.velcommuta.denul.networking.protobuf.c2s.StoreReply StoreReply = 4;</code>
     */
    boolean hasStoreReply();
    /**
     * <code>optional .de.velcommuta.denul.networking.protobuf.c2s.StoreReply StoreReply = 4;</code>
     */
    de.velcommuta.denul.networking.protobuf.c2s.C2S.StoreReply getStoreReply();
    /**
     * <code>optional .de.velcommuta.denul.networking.protobuf.c2s.StoreReply StoreReply = 4;</code>
     */
    de.velcommuta.denul.networking.protobuf.c2s.C2S.StoreReplyOrBuilder getStoreReplyOrBuilder();

    /**
     * <code>optional .de.velcommuta.denul.networking.protobuf.c2s.Get Get = 5;</code>
     */
    boolean hasGet();
    /**
     * <code>optional .de.velcommuta.denul.networking.protobuf.c2s.Get Get = 5;</code>
     */
    de.velcommuta.denul.networking.protobuf.c2s.C2S.Get getGet();
    /**
     * <code>optional .de.velcommuta.denul.networking.protobuf.c2s.Get Get = 5;</code>
     */
    de.velcommuta.denul.networking.protobuf.c2s.C2S.GetOrBuilder getGetOrBuilder();

    /**
     * <code>optional .de.velcommuta.denul.networking.protobuf.c2s.GetReply GetReply = 6;</code>
     */
    boolean hasGetReply();
    /**
     * <code>optional .de.velcommuta.denul.networking.protobuf.c2s.GetReply GetReply = 6;</code>
     */
    de.velcommuta.denul.networking.protobuf.c2s.C2S.GetReply getGetReply();
    /**
     * <code>optional .de.velcommuta.denul.networking.protobuf.c2s.GetReply GetReply = 6;</code>
     */
    de.velcommuta.denul.networking.protobuf.c2s.C2S.GetReplyOrBuilder getGetReplyOrBuilder();

    /**
     * <code>optional .de.velcommuta.denul.networking.protobuf.c2s.Delete Delete = 7;</code>
     */
    boolean hasDelete();
    /**
     * <code>optional .de.velcommuta.denul.networking.protobuf.c2s.Delete Delete = 7;</code>
     */
    de.velcommuta.denul.networking.protobuf.c2s.C2S.Delete getDelete();
    /**
     * <code>optional .de.velcommuta.denul.networking.protobuf.c2s.Delete Delete = 7;</code>
     */
    de.velcommuta.denul.networking.protobuf.c2s.C2S.DeleteOrBuilder getDeleteOrBuilder();

    /**
     * <code>optional .de.velcommuta.denul.networking.protobuf.c2s.DeleteReply DeleteReply = 8;</code>
     */
    boolean hasDeleteReply();
    /**
     * <code>optional .de.velcommuta.denul.networking.protobuf.c2s.DeleteReply DeleteReply = 8;</code>
     */
    de.velcommuta.denul.networking.protobuf.c2s.C2S.DeleteReply getDeleteReply();
    /**
     * <code>optional .de.velcommuta.denul.networking.protobuf.c2s.DeleteReply DeleteReply = 8;</code>
     */
    de.velcommuta.denul.networking.protobuf.c2s.C2S.DeleteReplyOrBuilder getDeleteReplyOrBuilder();
  }
  /**
   * Protobuf type {@code de.velcommuta.denul.networking.protobuf.meta.Wrapper}
   *
   * <pre>
   * Wrapper Message
   * This message contains another message
   * This is used to ensure that we only ever have to
   * expect one message type coming from the network
   * </pre>
   */
  public static final class Wrapper extends
      com.google.protobuf.GeneratedMessage implements
      // @@protoc_insertion_point(message_implements:de.velcommuta.denul.networking.protobuf.meta.Wrapper)
      WrapperOrBuilder {
    // Use Wrapper.newBuilder() to construct.
    private Wrapper(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
      super(builder);
      this.unknownFields = builder.getUnknownFields();
    }
    private Wrapper(boolean noInit) { this.unknownFields = com.google.protobuf.UnknownFieldSet.getDefaultInstance(); }

    private static final Wrapper defaultInstance;
    public static Wrapper getDefaultInstance() {
      return defaultInstance;
    }

    public Wrapper getDefaultInstanceForType() {
      return defaultInstance;
    }

    private final com.google.protobuf.UnknownFieldSet unknownFields;
    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
        getUnknownFields() {
      return this.unknownFields;
    }
    private Wrapper(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      initFields();
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
            case 10: {
              de.velcommuta.denul.networking.protobuf.c2s.C2S.ClientHello.Builder subBuilder = null;
              if (messageCase_ == 1) {
                subBuilder = ((de.velcommuta.denul.networking.protobuf.c2s.C2S.ClientHello) message_).toBuilder();
              }
              message_ = input.readMessage(de.velcommuta.denul.networking.protobuf.c2s.C2S.ClientHello.PARSER, extensionRegistry);
              if (subBuilder != null) {
                subBuilder.mergeFrom((de.velcommuta.denul.networking.protobuf.c2s.C2S.ClientHello) message_);
                message_ = subBuilder.buildPartial();
              }
              messageCase_ = 1;
              break;
            }
            case 18: {
              de.velcommuta.denul.networking.protobuf.c2s.C2S.ServerHello.Builder subBuilder = null;
              if (messageCase_ == 2) {
                subBuilder = ((de.velcommuta.denul.networking.protobuf.c2s.C2S.ServerHello) message_).toBuilder();
              }
              message_ = input.readMessage(de.velcommuta.denul.networking.protobuf.c2s.C2S.ServerHello.PARSER, extensionRegistry);
              if (subBuilder != null) {
                subBuilder.mergeFrom((de.velcommuta.denul.networking.protobuf.c2s.C2S.ServerHello) message_);
                message_ = subBuilder.buildPartial();
              }
              messageCase_ = 2;
              break;
            }
            case 26: {
              de.velcommuta.denul.networking.protobuf.c2s.C2S.Store.Builder subBuilder = null;
              if (messageCase_ == 3) {
                subBuilder = ((de.velcommuta.denul.networking.protobuf.c2s.C2S.Store) message_).toBuilder();
              }
              message_ = input.readMessage(de.velcommuta.denul.networking.protobuf.c2s.C2S.Store.PARSER, extensionRegistry);
              if (subBuilder != null) {
                subBuilder.mergeFrom((de.velcommuta.denul.networking.protobuf.c2s.C2S.Store) message_);
                message_ = subBuilder.buildPartial();
              }
              messageCase_ = 3;
              break;
            }
            case 34: {
              de.velcommuta.denul.networking.protobuf.c2s.C2S.StoreReply.Builder subBuilder = null;
              if (messageCase_ == 4) {
                subBuilder = ((de.velcommuta.denul.networking.protobuf.c2s.C2S.StoreReply) message_).toBuilder();
              }
              message_ = input.readMessage(de.velcommuta.denul.networking.protobuf.c2s.C2S.StoreReply.PARSER, extensionRegistry);
              if (subBuilder != null) {
                subBuilder.mergeFrom((de.velcommuta.denul.networking.protobuf.c2s.C2S.StoreReply) message_);
                message_ = subBuilder.buildPartial();
              }
              messageCase_ = 4;
              break;
            }
            case 42: {
              de.velcommuta.denul.networking.protobuf.c2s.C2S.Get.Builder subBuilder = null;
              if (messageCase_ == 5) {
                subBuilder = ((de.velcommuta.denul.networking.protobuf.c2s.C2S.Get) message_).toBuilder();
              }
              message_ = input.readMessage(de.velcommuta.denul.networking.protobuf.c2s.C2S.Get.PARSER, extensionRegistry);
              if (subBuilder != null) {
                subBuilder.mergeFrom((de.velcommuta.denul.networking.protobuf.c2s.C2S.Get) message_);
                message_ = subBuilder.buildPartial();
              }
              messageCase_ = 5;
              break;
            }
            case 50: {
              de.velcommuta.denul.networking.protobuf.c2s.C2S.GetReply.Builder subBuilder = null;
              if (messageCase_ == 6) {
                subBuilder = ((de.velcommuta.denul.networking.protobuf.c2s.C2S.GetReply) message_).toBuilder();
              }
              message_ = input.readMessage(de.velcommuta.denul.networking.protobuf.c2s.C2S.GetReply.PARSER, extensionRegistry);
              if (subBuilder != null) {
                subBuilder.mergeFrom((de.velcommuta.denul.networking.protobuf.c2s.C2S.GetReply) message_);
                message_ = subBuilder.buildPartial();
              }
              messageCase_ = 6;
              break;
            }
            case 58: {
              de.velcommuta.denul.networking.protobuf.c2s.C2S.Delete.Builder subBuilder = null;
              if (messageCase_ == 7) {
                subBuilder = ((de.velcommuta.denul.networking.protobuf.c2s.C2S.Delete) message_).toBuilder();
              }
              message_ = input.readMessage(de.velcommuta.denul.networking.protobuf.c2s.C2S.Delete.PARSER, extensionRegistry);
              if (subBuilder != null) {
                subBuilder.mergeFrom((de.velcommuta.denul.networking.protobuf.c2s.C2S.Delete) message_);
                message_ = subBuilder.buildPartial();
              }
              messageCase_ = 7;
              break;
            }
            case 66: {
              de.velcommuta.denul.networking.protobuf.c2s.C2S.DeleteReply.Builder subBuilder = null;
              if (messageCase_ == 8) {
                subBuilder = ((de.velcommuta.denul.networking.protobuf.c2s.C2S.DeleteReply) message_).toBuilder();
              }
              message_ = input.readMessage(de.velcommuta.denul.networking.protobuf.c2s.C2S.DeleteReply.PARSER, extensionRegistry);
              if (subBuilder != null) {
                subBuilder.mergeFrom((de.velcommuta.denul.networking.protobuf.c2s.C2S.DeleteReply) message_);
                message_ = subBuilder.buildPartial();
              }
              messageCase_ = 8;
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e.getMessage()).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return de.velcommuta.denul.networking.protobuf.meta.MetaMessage.internal_static_de_velcommuta_denul_networking_protobuf_meta_Wrapper_descriptor;
    }

    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return de.velcommuta.denul.networking.protobuf.meta.MetaMessage.internal_static_de_velcommuta_denul_networking_protobuf_meta_Wrapper_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              de.velcommuta.denul.networking.protobuf.meta.MetaMessage.Wrapper.class, de.velcommuta.denul.networking.protobuf.meta.MetaMessage.Wrapper.Builder.class);
    }

    public static com.google.protobuf.Parser<Wrapper> PARSER =
        new com.google.protobuf.AbstractParser<Wrapper>() {
      public Wrapper parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new Wrapper(input, extensionRegistry);
      }
    };

    @java.lang.Override
    public com.google.protobuf.Parser<Wrapper> getParserForType() {
      return PARSER;
    }

    private int bitField0_;
    private int messageCase_ = 0;
    private java.lang.Object message_;
    public enum MessageCase
        implements com.google.protobuf.Internal.EnumLite {
      CLIENTHELLO(1),
      SERVERHELLO(2),
      STORE(3),
      STOREREPLY(4),
      GET(5),
      GETREPLY(6),
      DELETE(7),
      DELETEREPLY(8),
      MESSAGE_NOT_SET(0);
      private int value = 0;
      private MessageCase(int value) {
        this.value = value;
      }
      public static MessageCase valueOf(int value) {
        switch (value) {
          case 1: return CLIENTHELLO;
          case 2: return SERVERHELLO;
          case 3: return STORE;
          case 4: return STOREREPLY;
          case 5: return GET;
          case 6: return GETREPLY;
          case 7: return DELETE;
          case 8: return DELETEREPLY;
          case 0: return MESSAGE_NOT_SET;
          default: throw new java.lang.IllegalArgumentException(
            "Value is undefined for this oneof enum.");
        }
      }
      public int getNumber() {
        return this.value;
      }
    };

    public MessageCase
    getMessageCase() {
      return MessageCase.valueOf(
          messageCase_);
    }

    public static final int CLIENTHELLO_FIELD_NUMBER = 1;
    /**
     * <code>optional .de.velcommuta.denul.networking.protobuf.c2s.ClientHello ClientHello = 1;</code>
     */
    public boolean hasClientHello() {
      return messageCase_ == 1;
    }
    /**
     * <code>optional .de.velcommuta.denul.networking.protobuf.c2s.ClientHello ClientHello = 1;</code>
     */
    public de.velcommuta.denul.networking.protobuf.c2s.C2S.ClientHello getClientHello() {
      if (messageCase_ == 1) {
         return (de.velcommuta.denul.networking.protobuf.c2s.C2S.ClientHello) message_;
      }
      return de.velcommuta.denul.networking.protobuf.c2s.C2S.ClientHello.getDefaultInstance();
    }
    /**
     * <code>optional .de.velcommuta.denul.networking.protobuf.c2s.ClientHello ClientHello = 1;</code>
     */
    public de.velcommuta.denul.networking.protobuf.c2s.C2S.ClientHelloOrBuilder getClientHelloOrBuilder() {
      if (messageCase_ == 1) {
         return (de.velcommuta.denul.networking.protobuf.c2s.C2S.ClientHello) message_;
      }
      return de.velcommuta.denul.networking.protobuf.c2s.C2S.ClientHello.getDefaultInstance();
    }

    public static final int SERVERHELLO_FIELD_NUMBER = 2;
    /**
     * <code>optional .de.velcommuta.denul.networking.protobuf.c2s.ServerHello ServerHello = 2;</code>
     */
    public boolean hasServerHello() {
      return messageCase_ == 2;
    }
    /**
     * <code>optional .de.velcommuta.denul.networking.protobuf.c2s.ServerHello ServerHello = 2;</code>
     */
    public de.velcommuta.denul.networking.protobuf.c2s.C2S.ServerHello getServerHello() {
      if (messageCase_ == 2) {
         return (de.velcommuta.denul.networking.protobuf.c2s.C2S.ServerHello) message_;
      }
      return de.velcommuta.denul.networking.protobuf.c2s.C2S.ServerHello.getDefaultInstance();
    }
    /**
     * <code>optional .de.velcommuta.denul.networking.protobuf.c2s.ServerHello ServerHello = 2;</code>
     */
    public de.velcommuta.denul.networking.protobuf.c2s.C2S.ServerHelloOrBuilder getServerHelloOrBuilder() {
      if (messageCase_ == 2) {
         return (de.velcommuta.denul.networking.protobuf.c2s.C2S.ServerHello) message_;
      }
      return de.velcommuta.denul.networking.protobuf.c2s.C2S.ServerHello.getDefaultInstance();
    }

    public static final int STORE_FIELD_NUMBER = 3;
    /**
     * <code>optional .de.velcommuta.denul.networking.protobuf.c2s.Store Store = 3;</code>
     */
    public boolean hasStore() {
      return messageCase_ == 3;
    }
    /**
     * <code>optional .de.velcommuta.denul.networking.protobuf.c2s.Store Store = 3;</code>
     */
    public de.velcommuta.denul.networking.protobuf.c2s.C2S.Store getStore() {
      if (messageCase_ == 3) {
         return (de.velcommuta.denul.networking.protobuf.c2s.C2S.Store) message_;
      }
      return de.velcommuta.denul.networking.protobuf.c2s.C2S.Store.getDefaultInstance();
    }
    /**
     * <code>optional .de.velcommuta.denul.networking.protobuf.c2s.Store Store = 3;</code>
     */
    public de.velcommuta.denul.networking.protobuf.c2s.C2S.StoreOrBuilder getStoreOrBuilder() {
      if (messageCase_ == 3) {
         return (de.velcommuta.denul.networking.protobuf.c2s.C2S.Store) message_;
      }
      return de.velcommuta.denul.networking.protobuf.c2s.C2S.Store.getDefaultInstance();
    }

    public static final int STOREREPLY_FIELD_NUMBER = 4;
    /**
     * <code>optional .de.velcommuta.denul.networking.protobuf.c2s.StoreReply StoreReply = 4;</code>
     */
    public boolean hasStoreReply() {
      return messageCase_ == 4;
    }
    /**
     * <code>optional .de.velcommuta.denul.networking.protobuf.c2s.StoreReply StoreReply = 4;</code>
     */
    public de.velcommuta.denul.networking.protobuf.c2s.C2S.StoreReply getStoreReply() {
      if (messageCase_ == 4) {
         return (de.velcommuta.denul.networking.protobuf.c2s.C2S.StoreReply) message_;
      }
      return de.velcommuta.denul.networking.protobuf.c2s.C2S.StoreReply.getDefaultInstance();
    }
    /**
     * <code>optional .de.velcommuta.denul.networking.protobuf.c2s.StoreReply StoreReply = 4;</code>
     */
    public de.velcommuta.denul.networking.protobuf.c2s.C2S.StoreReplyOrBuilder getStoreReplyOrBuilder() {
      if (messageCase_ == 4) {
         return (de.velcommuta.denul.networking.protobuf.c2s.C2S.StoreReply) message_;
      }
      return de.velcommuta.denul.networking.protobuf.c2s.C2S.StoreReply.getDefaultInstance();
    }

    public static final int GET_FIELD_NUMBER = 5;
    /**
     * <code>optional .de.velcommuta.denul.networking.protobuf.c2s.Get Get = 5;</code>
     */
    public boolean hasGet() {
      return messageCase_ == 5;
    }
    /**
     * <code>optional .de.velcommuta.denul.networking.protobuf.c2s.Get Get = 5;</code>
     */
    public de.velcommuta.denul.networking.protobuf.c2s.C2S.Get getGet() {
      if (messageCase_ == 5) {
         return (de.velcommuta.denul.networking.protobuf.c2s.C2S.Get) message_;
      }
      return de.velcommuta.denul.networking.protobuf.c2s.C2S.Get.getDefaultInstance();
    }
    /**
     * <code>optional .de.velcommuta.denul.networking.protobuf.c2s.Get Get = 5;</code>
     */
    public de.velcommuta.denul.networking.protobuf.c2s.C2S.GetOrBuilder getGetOrBuilder() {
      if (messageCase_ == 5) {
         return (de.velcommuta.denul.networking.protobuf.c2s.C2S.Get) message_;
      }
      return de.velcommuta.denul.networking.protobuf.c2s.C2S.Get.getDefaultInstance();
    }

    public static final int GETREPLY_FIELD_NUMBER = 6;
    /**
     * <code>optional .de.velcommuta.denul.networking.protobuf.c2s.GetReply GetReply = 6;</code>
     */
    public boolean hasGetReply() {
      return messageCase_ == 6;
    }
    /**
     * <code>optional .de.velcommuta.denul.networking.protobuf.c2s.GetReply GetReply = 6;</code>
     */
    public de.velcommuta.denul.networking.protobuf.c2s.C2S.GetReply getGetReply() {
      if (messageCase_ == 6) {
         return (de.velcommuta.denul.networking.protobuf.c2s.C2S.GetReply) message_;
      }
      return de.velcommuta.denul.networking.protobuf.c2s.C2S.GetReply.getDefaultInstance();
    }
    /**
     * <code>optional .de.velcommuta.denul.networking.protobuf.c2s.GetReply GetReply = 6;</code>
     */
    public de.velcommuta.denul.networking.protobuf.c2s.C2S.GetReplyOrBuilder getGetReplyOrBuilder() {
      if (messageCase_ == 6) {
         return (de.velcommuta.denul.networking.protobuf.c2s.C2S.GetReply) message_;
      }
      return de.velcommuta.denul.networking.protobuf.c2s.C2S.GetReply.getDefaultInstance();
    }

    public static final int DELETE_FIELD_NUMBER = 7;
    /**
     * <code>optional .de.velcommuta.denul.networking.protobuf.c2s.Delete Delete = 7;</code>
     */
    public boolean hasDelete() {
      return messageCase_ == 7;
    }
    /**
     * <code>optional .de.velcommuta.denul.networking.protobuf.c2s.Delete Delete = 7;</code>
     */
    public de.velcommuta.denul.networking.protobuf.c2s.C2S.Delete getDelete() {
      if (messageCase_ == 7) {
         return (de.velcommuta.denul.networking.protobuf.c2s.C2S.Delete) message_;
      }
      return de.velcommuta.denul.networking.protobuf.c2s.C2S.Delete.getDefaultInstance();
    }
    /**
     * <code>optional .de.velcommuta.denul.networking.protobuf.c2s.Delete Delete = 7;</code>
     */
    public de.velcommuta.denul.networking.protobuf.c2s.C2S.DeleteOrBuilder getDeleteOrBuilder() {
      if (messageCase_ == 7) {
         return (de.velcommuta.denul.networking.protobuf.c2s.C2S.Delete) message_;
      }
      return de.velcommuta.denul.networking.protobuf.c2s.C2S.Delete.getDefaultInstance();
    }

    public static final int DELETEREPLY_FIELD_NUMBER = 8;
    /**
     * <code>optional .de.velcommuta.denul.networking.protobuf.c2s.DeleteReply DeleteReply = 8;</code>
     */
    public boolean hasDeleteReply() {
      return messageCase_ == 8;
    }
    /**
     * <code>optional .de.velcommuta.denul.networking.protobuf.c2s.DeleteReply DeleteReply = 8;</code>
     */
    public de.velcommuta.denul.networking.protobuf.c2s.C2S.DeleteReply getDeleteReply() {
      if (messageCase_ == 8) {
         return (de.velcommuta.denul.networking.protobuf.c2s.C2S.DeleteReply) message_;
      }
      return de.velcommuta.denul.networking.protobuf.c2s.C2S.DeleteReply.getDefaultInstance();
    }
    /**
     * <code>optional .de.velcommuta.denul.networking.protobuf.c2s.DeleteReply DeleteReply = 8;</code>
     */
    public de.velcommuta.denul.networking.protobuf.c2s.C2S.DeleteReplyOrBuilder getDeleteReplyOrBuilder() {
      if (messageCase_ == 8) {
         return (de.velcommuta.denul.networking.protobuf.c2s.C2S.DeleteReply) message_;
      }
      return de.velcommuta.denul.networking.protobuf.c2s.C2S.DeleteReply.getDefaultInstance();
    }

    private void initFields() {
    }
    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      if (hasClientHello()) {
        if (!getClientHello().isInitialized()) {
          memoizedIsInitialized = 0;
          return false;
        }
      }
      if (hasServerHello()) {
        if (!getServerHello().isInitialized()) {
          memoizedIsInitialized = 0;
          return false;
        }
      }
      if (hasStore()) {
        if (!getStore().isInitialized()) {
          memoizedIsInitialized = 0;
          return false;
        }
      }
      if (hasStoreReply()) {
        if (!getStoreReply().isInitialized()) {
          memoizedIsInitialized = 0;
          return false;
        }
      }
      if (hasGet()) {
        if (!getGet().isInitialized()) {
          memoizedIsInitialized = 0;
          return false;
        }
      }
      if (hasGetReply()) {
        if (!getGetReply().isInitialized()) {
          memoizedIsInitialized = 0;
          return false;
        }
      }
      if (hasDelete()) {
        if (!getDelete().isInitialized()) {
          memoizedIsInitialized = 0;
          return false;
        }
      }
      if (hasDeleteReply()) {
        if (!getDeleteReply().isInitialized()) {
          memoizedIsInitialized = 0;
          return false;
        }
      }
      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      if (messageCase_ == 1) {
        output.writeMessage(1, (de.velcommuta.denul.networking.protobuf.c2s.C2S.ClientHello) message_);
      }
      if (messageCase_ == 2) {
        output.writeMessage(2, (de.velcommuta.denul.networking.protobuf.c2s.C2S.ServerHello) message_);
      }
      if (messageCase_ == 3) {
        output.writeMessage(3, (de.velcommuta.denul.networking.protobuf.c2s.C2S.Store) message_);
      }
      if (messageCase_ == 4) {
        output.writeMessage(4, (de.velcommuta.denul.networking.protobuf.c2s.C2S.StoreReply) message_);
      }
      if (messageCase_ == 5) {
        output.writeMessage(5, (de.velcommuta.denul.networking.protobuf.c2s.C2S.Get) message_);
      }
      if (messageCase_ == 6) {
        output.writeMessage(6, (de.velcommuta.denul.networking.protobuf.c2s.C2S.GetReply) message_);
      }
      if (messageCase_ == 7) {
        output.writeMessage(7, (de.velcommuta.denul.networking.protobuf.c2s.C2S.Delete) message_);
      }
      if (messageCase_ == 8) {
        output.writeMessage(8, (de.velcommuta.denul.networking.protobuf.c2s.C2S.DeleteReply) message_);
      }
      getUnknownFields().writeTo(output);
    }

    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;

      size = 0;
      if (messageCase_ == 1) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(1, (de.velcommuta.denul.networking.protobuf.c2s.C2S.ClientHello) message_);
      }
      if (messageCase_ == 2) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(2, (de.velcommuta.denul.networking.protobuf.c2s.C2S.ServerHello) message_);
      }
      if (messageCase_ == 3) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(3, (de.velcommuta.denul.networking.protobuf.c2s.C2S.Store) message_);
      }
      if (messageCase_ == 4) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(4, (de.velcommuta.denul.networking.protobuf.c2s.C2S.StoreReply) message_);
      }
      if (messageCase_ == 5) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(5, (de.velcommuta.denul.networking.protobuf.c2s.C2S.Get) message_);
      }
      if (messageCase_ == 6) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(6, (de.velcommuta.denul.networking.protobuf.c2s.C2S.GetReply) message_);
      }
      if (messageCase_ == 7) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(7, (de.velcommuta.denul.networking.protobuf.c2s.C2S.Delete) message_);
      }
      if (messageCase_ == 8) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(8, (de.velcommuta.denul.networking.protobuf.c2s.C2S.DeleteReply) message_);
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    @java.lang.Override
    protected java.lang.Object writeReplace()
        throws java.io.ObjectStreamException {
      return super.writeReplace();
    }

    public static de.velcommuta.denul.networking.protobuf.meta.MetaMessage.Wrapper parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static de.velcommuta.denul.networking.protobuf.meta.MetaMessage.Wrapper parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static de.velcommuta.denul.networking.protobuf.meta.MetaMessage.Wrapper parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static de.velcommuta.denul.networking.protobuf.meta.MetaMessage.Wrapper parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static de.velcommuta.denul.networking.protobuf.meta.MetaMessage.Wrapper parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static de.velcommuta.denul.networking.protobuf.meta.MetaMessage.Wrapper parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }
    public static de.velcommuta.denul.networking.protobuf.meta.MetaMessage.Wrapper parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input);
    }
    public static de.velcommuta.denul.networking.protobuf.meta.MetaMessage.Wrapper parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input, extensionRegistry);
    }
    public static de.velcommuta.denul.networking.protobuf.meta.MetaMessage.Wrapper parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static de.velcommuta.denul.networking.protobuf.meta.MetaMessage.Wrapper parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }

    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(de.velcommuta.denul.networking.protobuf.meta.MetaMessage.Wrapper prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code de.velcommuta.denul.networking.protobuf.meta.Wrapper}
     *
     * <pre>
     * Wrapper Message
     * This message contains another message
     * This is used to ensure that we only ever have to
     * expect one message type coming from the network
     * </pre>
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:de.velcommuta.denul.networking.protobuf.meta.Wrapper)
        de.velcommuta.denul.networking.protobuf.meta.MetaMessage.WrapperOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return de.velcommuta.denul.networking.protobuf.meta.MetaMessage.internal_static_de_velcommuta_denul_networking_protobuf_meta_Wrapper_descriptor;
      }

      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return de.velcommuta.denul.networking.protobuf.meta.MetaMessage.internal_static_de_velcommuta_denul_networking_protobuf_meta_Wrapper_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                de.velcommuta.denul.networking.protobuf.meta.MetaMessage.Wrapper.class, de.velcommuta.denul.networking.protobuf.meta.MetaMessage.Wrapper.Builder.class);
      }

      // Construct using MetaMessage.Wrapper.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessage.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
        }
      }
      private static Builder create() {
        return new Builder();
      }

      public Builder clear() {
        super.clear();
        messageCase_ = 0;
        message_ = null;
        return this;
      }

      public Builder clone() {
        return create().mergeFrom(buildPartial());
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return de.velcommuta.denul.networking.protobuf.meta.MetaMessage.internal_static_de_velcommuta_denul_networking_protobuf_meta_Wrapper_descriptor;
      }

      public de.velcommuta.denul.networking.protobuf.meta.MetaMessage.Wrapper getDefaultInstanceForType() {
        return de.velcommuta.denul.networking.protobuf.meta.MetaMessage.Wrapper.getDefaultInstance();
      }

      public de.velcommuta.denul.networking.protobuf.meta.MetaMessage.Wrapper build() {
        de.velcommuta.denul.networking.protobuf.meta.MetaMessage.Wrapper result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public de.velcommuta.denul.networking.protobuf.meta.MetaMessage.Wrapper buildPartial() {
        de.velcommuta.denul.networking.protobuf.meta.MetaMessage.Wrapper result = new de.velcommuta.denul.networking.protobuf.meta.MetaMessage.Wrapper(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (messageCase_ == 1) {
          if (clientHelloBuilder_ == null) {
            result.message_ = message_;
          } else {
            result.message_ = clientHelloBuilder_.build();
          }
        }
        if (messageCase_ == 2) {
          if (serverHelloBuilder_ == null) {
            result.message_ = message_;
          } else {
            result.message_ = serverHelloBuilder_.build();
          }
        }
        if (messageCase_ == 3) {
          if (storeBuilder_ == null) {
            result.message_ = message_;
          } else {
            result.message_ = storeBuilder_.build();
          }
        }
        if (messageCase_ == 4) {
          if (storeReplyBuilder_ == null) {
            result.message_ = message_;
          } else {
            result.message_ = storeReplyBuilder_.build();
          }
        }
        if (messageCase_ == 5) {
          if (getBuilder_ == null) {
            result.message_ = message_;
          } else {
            result.message_ = getBuilder_.build();
          }
        }
        if (messageCase_ == 6) {
          if (getReplyBuilder_ == null) {
            result.message_ = message_;
          } else {
            result.message_ = getReplyBuilder_.build();
          }
        }
        if (messageCase_ == 7) {
          if (deleteBuilder_ == null) {
            result.message_ = message_;
          } else {
            result.message_ = deleteBuilder_.build();
          }
        }
        if (messageCase_ == 8) {
          if (deleteReplyBuilder_ == null) {
            result.message_ = message_;
          } else {
            result.message_ = deleteReplyBuilder_.build();
          }
        }
        result.bitField0_ = to_bitField0_;
        result.messageCase_ = messageCase_;
        onBuilt();
        return result;
      }

      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof de.velcommuta.denul.networking.protobuf.meta.MetaMessage.Wrapper) {
          return mergeFrom((de.velcommuta.denul.networking.protobuf.meta.MetaMessage.Wrapper)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(de.velcommuta.denul.networking.protobuf.meta.MetaMessage.Wrapper other) {
        if (other == de.velcommuta.denul.networking.protobuf.meta.MetaMessage.Wrapper.getDefaultInstance()) return this;
        switch (other.getMessageCase()) {
          case CLIENTHELLO: {
            mergeClientHello(other.getClientHello());
            break;
          }
          case SERVERHELLO: {
            mergeServerHello(other.getServerHello());
            break;
          }
          case STORE: {
            mergeStore(other.getStore());
            break;
          }
          case STOREREPLY: {
            mergeStoreReply(other.getStoreReply());
            break;
          }
          case GET: {
            mergeGet(other.getGet());
            break;
          }
          case GETREPLY: {
            mergeGetReply(other.getGetReply());
            break;
          }
          case DELETE: {
            mergeDelete(other.getDelete());
            break;
          }
          case DELETEREPLY: {
            mergeDeleteReply(other.getDeleteReply());
            break;
          }
          case MESSAGE_NOT_SET: {
            break;
          }
        }
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }

      public final boolean isInitialized() {
        if (hasClientHello()) {
          if (!getClientHello().isInitialized()) {
            
            return false;
          }
        }
        if (hasServerHello()) {
          if (!getServerHello().isInitialized()) {
            
            return false;
          }
        }
        if (hasStore()) {
          if (!getStore().isInitialized()) {
            
            return false;
          }
        }
        if (hasStoreReply()) {
          if (!getStoreReply().isInitialized()) {
            
            return false;
          }
        }
        if (hasGet()) {
          if (!getGet().isInitialized()) {
            
            return false;
          }
        }
        if (hasGetReply()) {
          if (!getGetReply().isInitialized()) {
            
            return false;
          }
        }
        if (hasDelete()) {
          if (!getDelete().isInitialized()) {
            
            return false;
          }
        }
        if (hasDeleteReply()) {
          if (!getDeleteReply().isInitialized()) {
            
            return false;
          }
        }
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        de.velcommuta.denul.networking.protobuf.meta.MetaMessage.Wrapper parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (de.velcommuta.denul.networking.protobuf.meta.MetaMessage.Wrapper) e.getUnfinishedMessage();
          throw e;
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int messageCase_ = 0;
      private java.lang.Object message_;
      public MessageCase
          getMessageCase() {
        return MessageCase.valueOf(
            messageCase_);
      }

      public Builder clearMessage() {
        messageCase_ = 0;
        message_ = null;
        onChanged();
        return this;
      }

      private int bitField0_;

      private com.google.protobuf.SingleFieldBuilder<
          de.velcommuta.denul.networking.protobuf.c2s.C2S.ClientHello, de.velcommuta.denul.networking.protobuf.c2s.C2S.ClientHello.Builder, de.velcommuta.denul.networking.protobuf.c2s.C2S.ClientHelloOrBuilder> clientHelloBuilder_;
      /**
       * <code>optional .de.velcommuta.denul.networking.protobuf.c2s.ClientHello ClientHello = 1;</code>
       */
      public boolean hasClientHello() {
        return messageCase_ == 1;
      }
      /**
       * <code>optional .de.velcommuta.denul.networking.protobuf.c2s.ClientHello ClientHello = 1;</code>
       */
      public de.velcommuta.denul.networking.protobuf.c2s.C2S.ClientHello getClientHello() {
        if (clientHelloBuilder_ == null) {
          if (messageCase_ == 1) {
            return (de.velcommuta.denul.networking.protobuf.c2s.C2S.ClientHello) message_;
          }
          return de.velcommuta.denul.networking.protobuf.c2s.C2S.ClientHello.getDefaultInstance();
        } else {
          if (messageCase_ == 1) {
            return clientHelloBuilder_.getMessage();
          }
          return de.velcommuta.denul.networking.protobuf.c2s.C2S.ClientHello.getDefaultInstance();
        }
      }
      /**
       * <code>optional .de.velcommuta.denul.networking.protobuf.c2s.ClientHello ClientHello = 1;</code>
       */
      public Builder setClientHello(de.velcommuta.denul.networking.protobuf.c2s.C2S.ClientHello value) {
        if (clientHelloBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          message_ = value;
          onChanged();
        } else {
          clientHelloBuilder_.setMessage(value);
        }
        messageCase_ = 1;
        return this;
      }
      /**
       * <code>optional .de.velcommuta.denul.networking.protobuf.c2s.ClientHello ClientHello = 1;</code>
       */
      public Builder setClientHello(
          de.velcommuta.denul.networking.protobuf.c2s.C2S.ClientHello.Builder builderForValue) {
        if (clientHelloBuilder_ == null) {
          message_ = builderForValue.build();
          onChanged();
        } else {
          clientHelloBuilder_.setMessage(builderForValue.build());
        }
        messageCase_ = 1;
        return this;
      }
      /**
       * <code>optional .de.velcommuta.denul.networking.protobuf.c2s.ClientHello ClientHello = 1;</code>
       */
      public Builder mergeClientHello(de.velcommuta.denul.networking.protobuf.c2s.C2S.ClientHello value) {
        if (clientHelloBuilder_ == null) {
          if (messageCase_ == 1 &&
              message_ != de.velcommuta.denul.networking.protobuf.c2s.C2S.ClientHello.getDefaultInstance()) {
            message_ = de.velcommuta.denul.networking.protobuf.c2s.C2S.ClientHello.newBuilder((de.velcommuta.denul.networking.protobuf.c2s.C2S.ClientHello) message_)
                .mergeFrom(value).buildPartial();
          } else {
            message_ = value;
          }
          onChanged();
        } else {
          if (messageCase_ == 1) {
            clientHelloBuilder_.mergeFrom(value);
          }
          clientHelloBuilder_.setMessage(value);
        }
        messageCase_ = 1;
        return this;
      }
      /**
       * <code>optional .de.velcommuta.denul.networking.protobuf.c2s.ClientHello ClientHello = 1;</code>
       */
      public Builder clearClientHello() {
        if (clientHelloBuilder_ == null) {
          if (messageCase_ == 1) {
            messageCase_ = 0;
            message_ = null;
            onChanged();
          }
        } else {
          if (messageCase_ == 1) {
            messageCase_ = 0;
            message_ = null;
          }
          clientHelloBuilder_.clear();
        }
        return this;
      }
      /**
       * <code>optional .de.velcommuta.denul.networking.protobuf.c2s.ClientHello ClientHello = 1;</code>
       */
      public de.velcommuta.denul.networking.protobuf.c2s.C2S.ClientHello.Builder getClientHelloBuilder() {
        return getClientHelloFieldBuilder().getBuilder();
      }
      /**
       * <code>optional .de.velcommuta.denul.networking.protobuf.c2s.ClientHello ClientHello = 1;</code>
       */
      public de.velcommuta.denul.networking.protobuf.c2s.C2S.ClientHelloOrBuilder getClientHelloOrBuilder() {
        if ((messageCase_ == 1) && (clientHelloBuilder_ != null)) {
          return clientHelloBuilder_.getMessageOrBuilder();
        } else {
          if (messageCase_ == 1) {
            return (de.velcommuta.denul.networking.protobuf.c2s.C2S.ClientHello) message_;
          }
          return de.velcommuta.denul.networking.protobuf.c2s.C2S.ClientHello.getDefaultInstance();
        }
      }
      /**
       * <code>optional .de.velcommuta.denul.networking.protobuf.c2s.ClientHello ClientHello = 1;</code>
       */
      private com.google.protobuf.SingleFieldBuilder<
          de.velcommuta.denul.networking.protobuf.c2s.C2S.ClientHello, de.velcommuta.denul.networking.protobuf.c2s.C2S.ClientHello.Builder, de.velcommuta.denul.networking.protobuf.c2s.C2S.ClientHelloOrBuilder> 
          getClientHelloFieldBuilder() {
        if (clientHelloBuilder_ == null) {
          if (!(messageCase_ == 1)) {
            message_ = de.velcommuta.denul.networking.protobuf.c2s.C2S.ClientHello.getDefaultInstance();
          }
          clientHelloBuilder_ = new com.google.protobuf.SingleFieldBuilder<
              de.velcommuta.denul.networking.protobuf.c2s.C2S.ClientHello, de.velcommuta.denul.networking.protobuf.c2s.C2S.ClientHello.Builder, de.velcommuta.denul.networking.protobuf.c2s.C2S.ClientHelloOrBuilder>(
                  (de.velcommuta.denul.networking.protobuf.c2s.C2S.ClientHello) message_,
                  getParentForChildren(),
                  isClean());
          message_ = null;
        }
        messageCase_ = 1;
        return clientHelloBuilder_;
      }

      private com.google.protobuf.SingleFieldBuilder<
          de.velcommuta.denul.networking.protobuf.c2s.C2S.ServerHello, de.velcommuta.denul.networking.protobuf.c2s.C2S.ServerHello.Builder, de.velcommuta.denul.networking.protobuf.c2s.C2S.ServerHelloOrBuilder> serverHelloBuilder_;
      /**
       * <code>optional .de.velcommuta.denul.networking.protobuf.c2s.ServerHello ServerHello = 2;</code>
       */
      public boolean hasServerHello() {
        return messageCase_ == 2;
      }
      /**
       * <code>optional .de.velcommuta.denul.networking.protobuf.c2s.ServerHello ServerHello = 2;</code>
       */
      public de.velcommuta.denul.networking.protobuf.c2s.C2S.ServerHello getServerHello() {
        if (serverHelloBuilder_ == null) {
          if (messageCase_ == 2) {
            return (de.velcommuta.denul.networking.protobuf.c2s.C2S.ServerHello) message_;
          }
          return de.velcommuta.denul.networking.protobuf.c2s.C2S.ServerHello.getDefaultInstance();
        } else {
          if (messageCase_ == 2) {
            return serverHelloBuilder_.getMessage();
          }
          return de.velcommuta.denul.networking.protobuf.c2s.C2S.ServerHello.getDefaultInstance();
        }
      }
      /**
       * <code>optional .de.velcommuta.denul.networking.protobuf.c2s.ServerHello ServerHello = 2;</code>
       */
      public Builder setServerHello(de.velcommuta.denul.networking.protobuf.c2s.C2S.ServerHello value) {
        if (serverHelloBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          message_ = value;
          onChanged();
        } else {
          serverHelloBuilder_.setMessage(value);
        }
        messageCase_ = 2;
        return this;
      }
      /**
       * <code>optional .de.velcommuta.denul.networking.protobuf.c2s.ServerHello ServerHello = 2;</code>
       */
      public Builder setServerHello(
          de.velcommuta.denul.networking.protobuf.c2s.C2S.ServerHello.Builder builderForValue) {
        if (serverHelloBuilder_ == null) {
          message_ = builderForValue.build();
          onChanged();
        } else {
          serverHelloBuilder_.setMessage(builderForValue.build());
        }
        messageCase_ = 2;
        return this;
      }
      /**
       * <code>optional .de.velcommuta.denul.networking.protobuf.c2s.ServerHello ServerHello = 2;</code>
       */
      public Builder mergeServerHello(de.velcommuta.denul.networking.protobuf.c2s.C2S.ServerHello value) {
        if (serverHelloBuilder_ == null) {
          if (messageCase_ == 2 &&
              message_ != de.velcommuta.denul.networking.protobuf.c2s.C2S.ServerHello.getDefaultInstance()) {
            message_ = de.velcommuta.denul.networking.protobuf.c2s.C2S.ServerHello.newBuilder((de.velcommuta.denul.networking.protobuf.c2s.C2S.ServerHello) message_)
                .mergeFrom(value).buildPartial();
          } else {
            message_ = value;
          }
          onChanged();
        } else {
          if (messageCase_ == 2) {
            serverHelloBuilder_.mergeFrom(value);
          }
          serverHelloBuilder_.setMessage(value);
        }
        messageCase_ = 2;
        return this;
      }
      /**
       * <code>optional .de.velcommuta.denul.networking.protobuf.c2s.ServerHello ServerHello = 2;</code>
       */
      public Builder clearServerHello() {
        if (serverHelloBuilder_ == null) {
          if (messageCase_ == 2) {
            messageCase_ = 0;
            message_ = null;
            onChanged();
          }
        } else {
          if (messageCase_ == 2) {
            messageCase_ = 0;
            message_ = null;
          }
          serverHelloBuilder_.clear();
        }
        return this;
      }
      /**
       * <code>optional .de.velcommuta.denul.networking.protobuf.c2s.ServerHello ServerHello = 2;</code>
       */
      public de.velcommuta.denul.networking.protobuf.c2s.C2S.ServerHello.Builder getServerHelloBuilder() {
        return getServerHelloFieldBuilder().getBuilder();
      }
      /**
       * <code>optional .de.velcommuta.denul.networking.protobuf.c2s.ServerHello ServerHello = 2;</code>
       */
      public de.velcommuta.denul.networking.protobuf.c2s.C2S.ServerHelloOrBuilder getServerHelloOrBuilder() {
        if ((messageCase_ == 2) && (serverHelloBuilder_ != null)) {
          return serverHelloBuilder_.getMessageOrBuilder();
        } else {
          if (messageCase_ == 2) {
            return (de.velcommuta.denul.networking.protobuf.c2s.C2S.ServerHello) message_;
          }
          return de.velcommuta.denul.networking.protobuf.c2s.C2S.ServerHello.getDefaultInstance();
        }
      }
      /**
       * <code>optional .de.velcommuta.denul.networking.protobuf.c2s.ServerHello ServerHello = 2;</code>
       */
      private com.google.protobuf.SingleFieldBuilder<
          de.velcommuta.denul.networking.protobuf.c2s.C2S.ServerHello, de.velcommuta.denul.networking.protobuf.c2s.C2S.ServerHello.Builder, de.velcommuta.denul.networking.protobuf.c2s.C2S.ServerHelloOrBuilder> 
          getServerHelloFieldBuilder() {
        if (serverHelloBuilder_ == null) {
          if (!(messageCase_ == 2)) {
            message_ = de.velcommuta.denul.networking.protobuf.c2s.C2S.ServerHello.getDefaultInstance();
          }
          serverHelloBuilder_ = new com.google.protobuf.SingleFieldBuilder<
              de.velcommuta.denul.networking.protobuf.c2s.C2S.ServerHello, de.velcommuta.denul.networking.protobuf.c2s.C2S.ServerHello.Builder, de.velcommuta.denul.networking.protobuf.c2s.C2S.ServerHelloOrBuilder>(
                  (de.velcommuta.denul.networking.protobuf.c2s.C2S.ServerHello) message_,
                  getParentForChildren(),
                  isClean());
          message_ = null;
        }
        messageCase_ = 2;
        return serverHelloBuilder_;
      }

      private com.google.protobuf.SingleFieldBuilder<
          de.velcommuta.denul.networking.protobuf.c2s.C2S.Store, de.velcommuta.denul.networking.protobuf.c2s.C2S.Store.Builder, de.velcommuta.denul.networking.protobuf.c2s.C2S.StoreOrBuilder> storeBuilder_;
      /**
       * <code>optional .de.velcommuta.denul.networking.protobuf.c2s.Store Store = 3;</code>
       */
      public boolean hasStore() {
        return messageCase_ == 3;
      }
      /**
       * <code>optional .de.velcommuta.denul.networking.protobuf.c2s.Store Store = 3;</code>
       */
      public de.velcommuta.denul.networking.protobuf.c2s.C2S.Store getStore() {
        if (storeBuilder_ == null) {
          if (messageCase_ == 3) {
            return (de.velcommuta.denul.networking.protobuf.c2s.C2S.Store) message_;
          }
          return de.velcommuta.denul.networking.protobuf.c2s.C2S.Store.getDefaultInstance();
        } else {
          if (messageCase_ == 3) {
            return storeBuilder_.getMessage();
          }
          return de.velcommuta.denul.networking.protobuf.c2s.C2S.Store.getDefaultInstance();
        }
      }
      /**
       * <code>optional .de.velcommuta.denul.networking.protobuf.c2s.Store Store = 3;</code>
       */
      public Builder setStore(de.velcommuta.denul.networking.protobuf.c2s.C2S.Store value) {
        if (storeBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          message_ = value;
          onChanged();
        } else {
          storeBuilder_.setMessage(value);
        }
        messageCase_ = 3;
        return this;
      }
      /**
       * <code>optional .de.velcommuta.denul.networking.protobuf.c2s.Store Store = 3;</code>
       */
      public Builder setStore(
          de.velcommuta.denul.networking.protobuf.c2s.C2S.Store.Builder builderForValue) {
        if (storeBuilder_ == null) {
          message_ = builderForValue.build();
          onChanged();
        } else {
          storeBuilder_.setMessage(builderForValue.build());
        }
        messageCase_ = 3;
        return this;
      }
      /**
       * <code>optional .de.velcommuta.denul.networking.protobuf.c2s.Store Store = 3;</code>
       */
      public Builder mergeStore(de.velcommuta.denul.networking.protobuf.c2s.C2S.Store value) {
        if (storeBuilder_ == null) {
          if (messageCase_ == 3 &&
              message_ != de.velcommuta.denul.networking.protobuf.c2s.C2S.Store.getDefaultInstance()) {
            message_ = de.velcommuta.denul.networking.protobuf.c2s.C2S.Store.newBuilder((de.velcommuta.denul.networking.protobuf.c2s.C2S.Store) message_)
                .mergeFrom(value).buildPartial();
          } else {
            message_ = value;
          }
          onChanged();
        } else {
          if (messageCase_ == 3) {
            storeBuilder_.mergeFrom(value);
          }
          storeBuilder_.setMessage(value);
        }
        messageCase_ = 3;
        return this;
      }
      /**
       * <code>optional .de.velcommuta.denul.networking.protobuf.c2s.Store Store = 3;</code>
       */
      public Builder clearStore() {
        if (storeBuilder_ == null) {
          if (messageCase_ == 3) {
            messageCase_ = 0;
            message_ = null;
            onChanged();
          }
        } else {
          if (messageCase_ == 3) {
            messageCase_ = 0;
            message_ = null;
          }
          storeBuilder_.clear();
        }
        return this;
      }
      /**
       * <code>optional .de.velcommuta.denul.networking.protobuf.c2s.Store Store = 3;</code>
       */
      public de.velcommuta.denul.networking.protobuf.c2s.C2S.Store.Builder getStoreBuilder() {
        return getStoreFieldBuilder().getBuilder();
      }
      /**
       * <code>optional .de.velcommuta.denul.networking.protobuf.c2s.Store Store = 3;</code>
       */
      public de.velcommuta.denul.networking.protobuf.c2s.C2S.StoreOrBuilder getStoreOrBuilder() {
        if ((messageCase_ == 3) && (storeBuilder_ != null)) {
          return storeBuilder_.getMessageOrBuilder();
        } else {
          if (messageCase_ == 3) {
            return (de.velcommuta.denul.networking.protobuf.c2s.C2S.Store) message_;
          }
          return de.velcommuta.denul.networking.protobuf.c2s.C2S.Store.getDefaultInstance();
        }
      }
      /**
       * <code>optional .de.velcommuta.denul.networking.protobuf.c2s.Store Store = 3;</code>
       */
      private com.google.protobuf.SingleFieldBuilder<
          de.velcommuta.denul.networking.protobuf.c2s.C2S.Store, de.velcommuta.denul.networking.protobuf.c2s.C2S.Store.Builder, de.velcommuta.denul.networking.protobuf.c2s.C2S.StoreOrBuilder> 
          getStoreFieldBuilder() {
        if (storeBuilder_ == null) {
          if (!(messageCase_ == 3)) {
            message_ = de.velcommuta.denul.networking.protobuf.c2s.C2S.Store.getDefaultInstance();
          }
          storeBuilder_ = new com.google.protobuf.SingleFieldBuilder<
              de.velcommuta.denul.networking.protobuf.c2s.C2S.Store, de.velcommuta.denul.networking.protobuf.c2s.C2S.Store.Builder, de.velcommuta.denul.networking.protobuf.c2s.C2S.StoreOrBuilder>(
                  (de.velcommuta.denul.networking.protobuf.c2s.C2S.Store) message_,
                  getParentForChildren(),
                  isClean());
          message_ = null;
        }
        messageCase_ = 3;
        return storeBuilder_;
      }

      private com.google.protobuf.SingleFieldBuilder<
          de.velcommuta.denul.networking.protobuf.c2s.C2S.StoreReply, de.velcommuta.denul.networking.protobuf.c2s.C2S.StoreReply.Builder, de.velcommuta.denul.networking.protobuf.c2s.C2S.StoreReplyOrBuilder> storeReplyBuilder_;
      /**
       * <code>optional .de.velcommuta.denul.networking.protobuf.c2s.StoreReply StoreReply = 4;</code>
       */
      public boolean hasStoreReply() {
        return messageCase_ == 4;
      }
      /**
       * <code>optional .de.velcommuta.denul.networking.protobuf.c2s.StoreReply StoreReply = 4;</code>
       */
      public de.velcommuta.denul.networking.protobuf.c2s.C2S.StoreReply getStoreReply() {
        if (storeReplyBuilder_ == null) {
          if (messageCase_ == 4) {
            return (de.velcommuta.denul.networking.protobuf.c2s.C2S.StoreReply) message_;
          }
          return de.velcommuta.denul.networking.protobuf.c2s.C2S.StoreReply.getDefaultInstance();
        } else {
          if (messageCase_ == 4) {
            return storeReplyBuilder_.getMessage();
          }
          return de.velcommuta.denul.networking.protobuf.c2s.C2S.StoreReply.getDefaultInstance();
        }
      }
      /**
       * <code>optional .de.velcommuta.denul.networking.protobuf.c2s.StoreReply StoreReply = 4;</code>
       */
      public Builder setStoreReply(de.velcommuta.denul.networking.protobuf.c2s.C2S.StoreReply value) {
        if (storeReplyBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          message_ = value;
          onChanged();
        } else {
          storeReplyBuilder_.setMessage(value);
        }
        messageCase_ = 4;
        return this;
      }
      /**
       * <code>optional .de.velcommuta.denul.networking.protobuf.c2s.StoreReply StoreReply = 4;</code>
       */
      public Builder setStoreReply(
          de.velcommuta.denul.networking.protobuf.c2s.C2S.StoreReply.Builder builderForValue) {
        if (storeReplyBuilder_ == null) {
          message_ = builderForValue.build();
          onChanged();
        } else {
          storeReplyBuilder_.setMessage(builderForValue.build());
        }
        messageCase_ = 4;
        return this;
      }
      /**
       * <code>optional .de.velcommuta.denul.networking.protobuf.c2s.StoreReply StoreReply = 4;</code>
       */
      public Builder mergeStoreReply(de.velcommuta.denul.networking.protobuf.c2s.C2S.StoreReply value) {
        if (storeReplyBuilder_ == null) {
          if (messageCase_ == 4 &&
              message_ != de.velcommuta.denul.networking.protobuf.c2s.C2S.StoreReply.getDefaultInstance()) {
            message_ = de.velcommuta.denul.networking.protobuf.c2s.C2S.StoreReply.newBuilder((de.velcommuta.denul.networking.protobuf.c2s.C2S.StoreReply) message_)
                .mergeFrom(value).buildPartial();
          } else {
            message_ = value;
          }
          onChanged();
        } else {
          if (messageCase_ == 4) {
            storeReplyBuilder_.mergeFrom(value);
          }
          storeReplyBuilder_.setMessage(value);
        }
        messageCase_ = 4;
        return this;
      }
      /**
       * <code>optional .de.velcommuta.denul.networking.protobuf.c2s.StoreReply StoreReply = 4;</code>
       */
      public Builder clearStoreReply() {
        if (storeReplyBuilder_ == null) {
          if (messageCase_ == 4) {
            messageCase_ = 0;
            message_ = null;
            onChanged();
          }
        } else {
          if (messageCase_ == 4) {
            messageCase_ = 0;
            message_ = null;
          }
          storeReplyBuilder_.clear();
        }
        return this;
      }
      /**
       * <code>optional .de.velcommuta.denul.networking.protobuf.c2s.StoreReply StoreReply = 4;</code>
       */
      public de.velcommuta.denul.networking.protobuf.c2s.C2S.StoreReply.Builder getStoreReplyBuilder() {
        return getStoreReplyFieldBuilder().getBuilder();
      }
      /**
       * <code>optional .de.velcommuta.denul.networking.protobuf.c2s.StoreReply StoreReply = 4;</code>
       */
      public de.velcommuta.denul.networking.protobuf.c2s.C2S.StoreReplyOrBuilder getStoreReplyOrBuilder() {
        if ((messageCase_ == 4) && (storeReplyBuilder_ != null)) {
          return storeReplyBuilder_.getMessageOrBuilder();
        } else {
          if (messageCase_ == 4) {
            return (de.velcommuta.denul.networking.protobuf.c2s.C2S.StoreReply) message_;
          }
          return de.velcommuta.denul.networking.protobuf.c2s.C2S.StoreReply.getDefaultInstance();
        }
      }
      /**
       * <code>optional .de.velcommuta.denul.networking.protobuf.c2s.StoreReply StoreReply = 4;</code>
       */
      private com.google.protobuf.SingleFieldBuilder<
          de.velcommuta.denul.networking.protobuf.c2s.C2S.StoreReply, de.velcommuta.denul.networking.protobuf.c2s.C2S.StoreReply.Builder, de.velcommuta.denul.networking.protobuf.c2s.C2S.StoreReplyOrBuilder> 
          getStoreReplyFieldBuilder() {
        if (storeReplyBuilder_ == null) {
          if (!(messageCase_ == 4)) {
            message_ = de.velcommuta.denul.networking.protobuf.c2s.C2S.StoreReply.getDefaultInstance();
          }
          storeReplyBuilder_ = new com.google.protobuf.SingleFieldBuilder<
              de.velcommuta.denul.networking.protobuf.c2s.C2S.StoreReply, de.velcommuta.denul.networking.protobuf.c2s.C2S.StoreReply.Builder, de.velcommuta.denul.networking.protobuf.c2s.C2S.StoreReplyOrBuilder>(
                  (de.velcommuta.denul.networking.protobuf.c2s.C2S.StoreReply) message_,
                  getParentForChildren(),
                  isClean());
          message_ = null;
        }
        messageCase_ = 4;
        return storeReplyBuilder_;
      }

      private com.google.protobuf.SingleFieldBuilder<
          de.velcommuta.denul.networking.protobuf.c2s.C2S.Get, de.velcommuta.denul.networking.protobuf.c2s.C2S.Get.Builder, de.velcommuta.denul.networking.protobuf.c2s.C2S.GetOrBuilder> getBuilder_;
      /**
       * <code>optional .de.velcommuta.denul.networking.protobuf.c2s.Get Get = 5;</code>
       */
      public boolean hasGet() {
        return messageCase_ == 5;
      }
      /**
       * <code>optional .de.velcommuta.denul.networking.protobuf.c2s.Get Get = 5;</code>
       */
      public de.velcommuta.denul.networking.protobuf.c2s.C2S.Get getGet() {
        if (getBuilder_ == null) {
          if (messageCase_ == 5) {
            return (de.velcommuta.denul.networking.protobuf.c2s.C2S.Get) message_;
          }
          return de.velcommuta.denul.networking.protobuf.c2s.C2S.Get.getDefaultInstance();
        } else {
          if (messageCase_ == 5) {
            return getBuilder_.getMessage();
          }
          return de.velcommuta.denul.networking.protobuf.c2s.C2S.Get.getDefaultInstance();
        }
      }
      /**
       * <code>optional .de.velcommuta.denul.networking.protobuf.c2s.Get Get = 5;</code>
       */
      public Builder setGet(de.velcommuta.denul.networking.protobuf.c2s.C2S.Get value) {
        if (getBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          message_ = value;
          onChanged();
        } else {
          getBuilder_.setMessage(value);
        }
        messageCase_ = 5;
        return this;
      }
      /**
       * <code>optional .de.velcommuta.denul.networking.protobuf.c2s.Get Get = 5;</code>
       */
      public Builder setGet(
          de.velcommuta.denul.networking.protobuf.c2s.C2S.Get.Builder builderForValue) {
        if (getBuilder_ == null) {
          message_ = builderForValue.build();
          onChanged();
        } else {
          getBuilder_.setMessage(builderForValue.build());
        }
        messageCase_ = 5;
        return this;
      }
      /**
       * <code>optional .de.velcommuta.denul.networking.protobuf.c2s.Get Get = 5;</code>
       */
      public Builder mergeGet(de.velcommuta.denul.networking.protobuf.c2s.C2S.Get value) {
        if (getBuilder_ == null) {
          if (messageCase_ == 5 &&
              message_ != de.velcommuta.denul.networking.protobuf.c2s.C2S.Get.getDefaultInstance()) {
            message_ = de.velcommuta.denul.networking.protobuf.c2s.C2S.Get.newBuilder((de.velcommuta.denul.networking.protobuf.c2s.C2S.Get) message_)
                .mergeFrom(value).buildPartial();
          } else {
            message_ = value;
          }
          onChanged();
        } else {
          if (messageCase_ == 5) {
            getBuilder_.mergeFrom(value);
          }
          getBuilder_.setMessage(value);
        }
        messageCase_ = 5;
        return this;
      }
      /**
       * <code>optional .de.velcommuta.denul.networking.protobuf.c2s.Get Get = 5;</code>
       */
      public Builder clearGet() {
        if (getBuilder_ == null) {
          if (messageCase_ == 5) {
            messageCase_ = 0;
            message_ = null;
            onChanged();
          }
        } else {
          if (messageCase_ == 5) {
            messageCase_ = 0;
            message_ = null;
          }
          getBuilder_.clear();
        }
        return this;
      }
      /**
       * <code>optional .de.velcommuta.denul.networking.protobuf.c2s.Get Get = 5;</code>
       */
      public de.velcommuta.denul.networking.protobuf.c2s.C2S.Get.Builder getGetBuilder() {
        return getGetFieldBuilder().getBuilder();
      }
      /**
       * <code>optional .de.velcommuta.denul.networking.protobuf.c2s.Get Get = 5;</code>
       */
      public de.velcommuta.denul.networking.protobuf.c2s.C2S.GetOrBuilder getGetOrBuilder() {
        if ((messageCase_ == 5) && (getBuilder_ != null)) {
          return getBuilder_.getMessageOrBuilder();
        } else {
          if (messageCase_ == 5) {
            return (de.velcommuta.denul.networking.protobuf.c2s.C2S.Get) message_;
          }
          return de.velcommuta.denul.networking.protobuf.c2s.C2S.Get.getDefaultInstance();
        }
      }
      /**
       * <code>optional .de.velcommuta.denul.networking.protobuf.c2s.Get Get = 5;</code>
       */
      private com.google.protobuf.SingleFieldBuilder<
          de.velcommuta.denul.networking.protobuf.c2s.C2S.Get, de.velcommuta.denul.networking.protobuf.c2s.C2S.Get.Builder, de.velcommuta.denul.networking.protobuf.c2s.C2S.GetOrBuilder> 
          getGetFieldBuilder() {
        if (getBuilder_ == null) {
          if (!(messageCase_ == 5)) {
            message_ = de.velcommuta.denul.networking.protobuf.c2s.C2S.Get.getDefaultInstance();
          }
          getBuilder_ = new com.google.protobuf.SingleFieldBuilder<
              de.velcommuta.denul.networking.protobuf.c2s.C2S.Get, de.velcommuta.denul.networking.protobuf.c2s.C2S.Get.Builder, de.velcommuta.denul.networking.protobuf.c2s.C2S.GetOrBuilder>(
                  (de.velcommuta.denul.networking.protobuf.c2s.C2S.Get) message_,
                  getParentForChildren(),
                  isClean());
          message_ = null;
        }
        messageCase_ = 5;
        return getBuilder_;
      }

      private com.google.protobuf.SingleFieldBuilder<
          de.velcommuta.denul.networking.protobuf.c2s.C2S.GetReply, de.velcommuta.denul.networking.protobuf.c2s.C2S.GetReply.Builder, de.velcommuta.denul.networking.protobuf.c2s.C2S.GetReplyOrBuilder> getReplyBuilder_;
      /**
       * <code>optional .de.velcommuta.denul.networking.protobuf.c2s.GetReply GetReply = 6;</code>
       */
      public boolean hasGetReply() {
        return messageCase_ == 6;
      }
      /**
       * <code>optional .de.velcommuta.denul.networking.protobuf.c2s.GetReply GetReply = 6;</code>
       */
      public de.velcommuta.denul.networking.protobuf.c2s.C2S.GetReply getGetReply() {
        if (getReplyBuilder_ == null) {
          if (messageCase_ == 6) {
            return (de.velcommuta.denul.networking.protobuf.c2s.C2S.GetReply) message_;
          }
          return de.velcommuta.denul.networking.protobuf.c2s.C2S.GetReply.getDefaultInstance();
        } else {
          if (messageCase_ == 6) {
            return getReplyBuilder_.getMessage();
          }
          return de.velcommuta.denul.networking.protobuf.c2s.C2S.GetReply.getDefaultInstance();
        }
      }
      /**
       * <code>optional .de.velcommuta.denul.networking.protobuf.c2s.GetReply GetReply = 6;</code>
       */
      public Builder setGetReply(de.velcommuta.denul.networking.protobuf.c2s.C2S.GetReply value) {
        if (getReplyBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          message_ = value;
          onChanged();
        } else {
          getReplyBuilder_.setMessage(value);
        }
        messageCase_ = 6;
        return this;
      }
      /**
       * <code>optional .de.velcommuta.denul.networking.protobuf.c2s.GetReply GetReply = 6;</code>
       */
      public Builder setGetReply(
          de.velcommuta.denul.networking.protobuf.c2s.C2S.GetReply.Builder builderForValue) {
        if (getReplyBuilder_ == null) {
          message_ = builderForValue.build();
          onChanged();
        } else {
          getReplyBuilder_.setMessage(builderForValue.build());
        }
        messageCase_ = 6;
        return this;
      }
      /**
       * <code>optional .de.velcommuta.denul.networking.protobuf.c2s.GetReply GetReply = 6;</code>
       */
      public Builder mergeGetReply(de.velcommuta.denul.networking.protobuf.c2s.C2S.GetReply value) {
        if (getReplyBuilder_ == null) {
          if (messageCase_ == 6 &&
              message_ != de.velcommuta.denul.networking.protobuf.c2s.C2S.GetReply.getDefaultInstance()) {
            message_ = de.velcommuta.denul.networking.protobuf.c2s.C2S.GetReply.newBuilder((de.velcommuta.denul.networking.protobuf.c2s.C2S.GetReply) message_)
                .mergeFrom(value).buildPartial();
          } else {
            message_ = value;
          }
          onChanged();
        } else {
          if (messageCase_ == 6) {
            getReplyBuilder_.mergeFrom(value);
          }
          getReplyBuilder_.setMessage(value);
        }
        messageCase_ = 6;
        return this;
      }
      /**
       * <code>optional .de.velcommuta.denul.networking.protobuf.c2s.GetReply GetReply = 6;</code>
       */
      public Builder clearGetReply() {
        if (getReplyBuilder_ == null) {
          if (messageCase_ == 6) {
            messageCase_ = 0;
            message_ = null;
            onChanged();
          }
        } else {
          if (messageCase_ == 6) {
            messageCase_ = 0;
            message_ = null;
          }
          getReplyBuilder_.clear();
        }
        return this;
      }
      /**
       * <code>optional .de.velcommuta.denul.networking.protobuf.c2s.GetReply GetReply = 6;</code>
       */
      public de.velcommuta.denul.networking.protobuf.c2s.C2S.GetReply.Builder getGetReplyBuilder() {
        return getGetReplyFieldBuilder().getBuilder();
      }
      /**
       * <code>optional .de.velcommuta.denul.networking.protobuf.c2s.GetReply GetReply = 6;</code>
       */
      public de.velcommuta.denul.networking.protobuf.c2s.C2S.GetReplyOrBuilder getGetReplyOrBuilder() {
        if ((messageCase_ == 6) && (getReplyBuilder_ != null)) {
          return getReplyBuilder_.getMessageOrBuilder();
        } else {
          if (messageCase_ == 6) {
            return (de.velcommuta.denul.networking.protobuf.c2s.C2S.GetReply) message_;
          }
          return de.velcommuta.denul.networking.protobuf.c2s.C2S.GetReply.getDefaultInstance();
        }
      }
      /**
       * <code>optional .de.velcommuta.denul.networking.protobuf.c2s.GetReply GetReply = 6;</code>
       */
      private com.google.protobuf.SingleFieldBuilder<
          de.velcommuta.denul.networking.protobuf.c2s.C2S.GetReply, de.velcommuta.denul.networking.protobuf.c2s.C2S.GetReply.Builder, de.velcommuta.denul.networking.protobuf.c2s.C2S.GetReplyOrBuilder> 
          getGetReplyFieldBuilder() {
        if (getReplyBuilder_ == null) {
          if (!(messageCase_ == 6)) {
            message_ = de.velcommuta.denul.networking.protobuf.c2s.C2S.GetReply.getDefaultInstance();
          }
          getReplyBuilder_ = new com.google.protobuf.SingleFieldBuilder<
              de.velcommuta.denul.networking.protobuf.c2s.C2S.GetReply, de.velcommuta.denul.networking.protobuf.c2s.C2S.GetReply.Builder, de.velcommuta.denul.networking.protobuf.c2s.C2S.GetReplyOrBuilder>(
                  (de.velcommuta.denul.networking.protobuf.c2s.C2S.GetReply) message_,
                  getParentForChildren(),
                  isClean());
          message_ = null;
        }
        messageCase_ = 6;
        return getReplyBuilder_;
      }

      private com.google.protobuf.SingleFieldBuilder<
          de.velcommuta.denul.networking.protobuf.c2s.C2S.Delete, de.velcommuta.denul.networking.protobuf.c2s.C2S.Delete.Builder, de.velcommuta.denul.networking.protobuf.c2s.C2S.DeleteOrBuilder> deleteBuilder_;
      /**
       * <code>optional .de.velcommuta.denul.networking.protobuf.c2s.Delete Delete = 7;</code>
       */
      public boolean hasDelete() {
        return messageCase_ == 7;
      }
      /**
       * <code>optional .de.velcommuta.denul.networking.protobuf.c2s.Delete Delete = 7;</code>
       */
      public de.velcommuta.denul.networking.protobuf.c2s.C2S.Delete getDelete() {
        if (deleteBuilder_ == null) {
          if (messageCase_ == 7) {
            return (de.velcommuta.denul.networking.protobuf.c2s.C2S.Delete) message_;
          }
          return de.velcommuta.denul.networking.protobuf.c2s.C2S.Delete.getDefaultInstance();
        } else {
          if (messageCase_ == 7) {
            return deleteBuilder_.getMessage();
          }
          return de.velcommuta.denul.networking.protobuf.c2s.C2S.Delete.getDefaultInstance();
        }
      }
      /**
       * <code>optional .de.velcommuta.denul.networking.protobuf.c2s.Delete Delete = 7;</code>
       */
      public Builder setDelete(de.velcommuta.denul.networking.protobuf.c2s.C2S.Delete value) {
        if (deleteBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          message_ = value;
          onChanged();
        } else {
          deleteBuilder_.setMessage(value);
        }
        messageCase_ = 7;
        return this;
      }
      /**
       * <code>optional .de.velcommuta.denul.networking.protobuf.c2s.Delete Delete = 7;</code>
       */
      public Builder setDelete(
          de.velcommuta.denul.networking.protobuf.c2s.C2S.Delete.Builder builderForValue) {
        if (deleteBuilder_ == null) {
          message_ = builderForValue.build();
          onChanged();
        } else {
          deleteBuilder_.setMessage(builderForValue.build());
        }
        messageCase_ = 7;
        return this;
      }
      /**
       * <code>optional .de.velcommuta.denul.networking.protobuf.c2s.Delete Delete = 7;</code>
       */
      public Builder mergeDelete(de.velcommuta.denul.networking.protobuf.c2s.C2S.Delete value) {
        if (deleteBuilder_ == null) {
          if (messageCase_ == 7 &&
              message_ != de.velcommuta.denul.networking.protobuf.c2s.C2S.Delete.getDefaultInstance()) {
            message_ = de.velcommuta.denul.networking.protobuf.c2s.C2S.Delete.newBuilder((de.velcommuta.denul.networking.protobuf.c2s.C2S.Delete) message_)
                .mergeFrom(value).buildPartial();
          } else {
            message_ = value;
          }
          onChanged();
        } else {
          if (messageCase_ == 7) {
            deleteBuilder_.mergeFrom(value);
          }
          deleteBuilder_.setMessage(value);
        }
        messageCase_ = 7;
        return this;
      }
      /**
       * <code>optional .de.velcommuta.denul.networking.protobuf.c2s.Delete Delete = 7;</code>
       */
      public Builder clearDelete() {
        if (deleteBuilder_ == null) {
          if (messageCase_ == 7) {
            messageCase_ = 0;
            message_ = null;
            onChanged();
          }
        } else {
          if (messageCase_ == 7) {
            messageCase_ = 0;
            message_ = null;
          }
          deleteBuilder_.clear();
        }
        return this;
      }
      /**
       * <code>optional .de.velcommuta.denul.networking.protobuf.c2s.Delete Delete = 7;</code>
       */
      public de.velcommuta.denul.networking.protobuf.c2s.C2S.Delete.Builder getDeleteBuilder() {
        return getDeleteFieldBuilder().getBuilder();
      }
      /**
       * <code>optional .de.velcommuta.denul.networking.protobuf.c2s.Delete Delete = 7;</code>
       */
      public de.velcommuta.denul.networking.protobuf.c2s.C2S.DeleteOrBuilder getDeleteOrBuilder() {
        if ((messageCase_ == 7) && (deleteBuilder_ != null)) {
          return deleteBuilder_.getMessageOrBuilder();
        } else {
          if (messageCase_ == 7) {
            return (de.velcommuta.denul.networking.protobuf.c2s.C2S.Delete) message_;
          }
          return de.velcommuta.denul.networking.protobuf.c2s.C2S.Delete.getDefaultInstance();
        }
      }
      /**
       * <code>optional .de.velcommuta.denul.networking.protobuf.c2s.Delete Delete = 7;</code>
       */
      private com.google.protobuf.SingleFieldBuilder<
          de.velcommuta.denul.networking.protobuf.c2s.C2S.Delete, de.velcommuta.denul.networking.protobuf.c2s.C2S.Delete.Builder, de.velcommuta.denul.networking.protobuf.c2s.C2S.DeleteOrBuilder> 
          getDeleteFieldBuilder() {
        if (deleteBuilder_ == null) {
          if (!(messageCase_ == 7)) {
            message_ = de.velcommuta.denul.networking.protobuf.c2s.C2S.Delete.getDefaultInstance();
          }
          deleteBuilder_ = new com.google.protobuf.SingleFieldBuilder<
              de.velcommuta.denul.networking.protobuf.c2s.C2S.Delete, de.velcommuta.denul.networking.protobuf.c2s.C2S.Delete.Builder, de.velcommuta.denul.networking.protobuf.c2s.C2S.DeleteOrBuilder>(
                  (de.velcommuta.denul.networking.protobuf.c2s.C2S.Delete) message_,
                  getParentForChildren(),
                  isClean());
          message_ = null;
        }
        messageCase_ = 7;
        return deleteBuilder_;
      }

      private com.google.protobuf.SingleFieldBuilder<
          de.velcommuta.denul.networking.protobuf.c2s.C2S.DeleteReply, de.velcommuta.denul.networking.protobuf.c2s.C2S.DeleteReply.Builder, de.velcommuta.denul.networking.protobuf.c2s.C2S.DeleteReplyOrBuilder> deleteReplyBuilder_;
      /**
       * <code>optional .de.velcommuta.denul.networking.protobuf.c2s.DeleteReply DeleteReply = 8;</code>
       */
      public boolean hasDeleteReply() {
        return messageCase_ == 8;
      }
      /**
       * <code>optional .de.velcommuta.denul.networking.protobuf.c2s.DeleteReply DeleteReply = 8;</code>
       */
      public de.velcommuta.denul.networking.protobuf.c2s.C2S.DeleteReply getDeleteReply() {
        if (deleteReplyBuilder_ == null) {
          if (messageCase_ == 8) {
            return (de.velcommuta.denul.networking.protobuf.c2s.C2S.DeleteReply) message_;
          }
          return de.velcommuta.denul.networking.protobuf.c2s.C2S.DeleteReply.getDefaultInstance();
        } else {
          if (messageCase_ == 8) {
            return deleteReplyBuilder_.getMessage();
          }
          return de.velcommuta.denul.networking.protobuf.c2s.C2S.DeleteReply.getDefaultInstance();
        }
      }
      /**
       * <code>optional .de.velcommuta.denul.networking.protobuf.c2s.DeleteReply DeleteReply = 8;</code>
       */
      public Builder setDeleteReply(de.velcommuta.denul.networking.protobuf.c2s.C2S.DeleteReply value) {
        if (deleteReplyBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          message_ = value;
          onChanged();
        } else {
          deleteReplyBuilder_.setMessage(value);
        }
        messageCase_ = 8;
        return this;
      }
      /**
       * <code>optional .de.velcommuta.denul.networking.protobuf.c2s.DeleteReply DeleteReply = 8;</code>
       */
      public Builder setDeleteReply(
          de.velcommuta.denul.networking.protobuf.c2s.C2S.DeleteReply.Builder builderForValue) {
        if (deleteReplyBuilder_ == null) {
          message_ = builderForValue.build();
          onChanged();
        } else {
          deleteReplyBuilder_.setMessage(builderForValue.build());
        }
        messageCase_ = 8;
        return this;
      }
      /**
       * <code>optional .de.velcommuta.denul.networking.protobuf.c2s.DeleteReply DeleteReply = 8;</code>
       */
      public Builder mergeDeleteReply(de.velcommuta.denul.networking.protobuf.c2s.C2S.DeleteReply value) {
        if (deleteReplyBuilder_ == null) {
          if (messageCase_ == 8 &&
              message_ != de.velcommuta.denul.networking.protobuf.c2s.C2S.DeleteReply.getDefaultInstance()) {
            message_ = de.velcommuta.denul.networking.protobuf.c2s.C2S.DeleteReply.newBuilder((de.velcommuta.denul.networking.protobuf.c2s.C2S.DeleteReply) message_)
                .mergeFrom(value).buildPartial();
          } else {
            message_ = value;
          }
          onChanged();
        } else {
          if (messageCase_ == 8) {
            deleteReplyBuilder_.mergeFrom(value);
          }
          deleteReplyBuilder_.setMessage(value);
        }
        messageCase_ = 8;
        return this;
      }
      /**
       * <code>optional .de.velcommuta.denul.networking.protobuf.c2s.DeleteReply DeleteReply = 8;</code>
       */
      public Builder clearDeleteReply() {
        if (deleteReplyBuilder_ == null) {
          if (messageCase_ == 8) {
            messageCase_ = 0;
            message_ = null;
            onChanged();
          }
        } else {
          if (messageCase_ == 8) {
            messageCase_ = 0;
            message_ = null;
          }
          deleteReplyBuilder_.clear();
        }
        return this;
      }
      /**
       * <code>optional .de.velcommuta.denul.networking.protobuf.c2s.DeleteReply DeleteReply = 8;</code>
       */
      public de.velcommuta.denul.networking.protobuf.c2s.C2S.DeleteReply.Builder getDeleteReplyBuilder() {
        return getDeleteReplyFieldBuilder().getBuilder();
      }
      /**
       * <code>optional .de.velcommuta.denul.networking.protobuf.c2s.DeleteReply DeleteReply = 8;</code>
       */
      public de.velcommuta.denul.networking.protobuf.c2s.C2S.DeleteReplyOrBuilder getDeleteReplyOrBuilder() {
        if ((messageCase_ == 8) && (deleteReplyBuilder_ != null)) {
          return deleteReplyBuilder_.getMessageOrBuilder();
        } else {
          if (messageCase_ == 8) {
            return (de.velcommuta.denul.networking.protobuf.c2s.C2S.DeleteReply) message_;
          }
          return de.velcommuta.denul.networking.protobuf.c2s.C2S.DeleteReply.getDefaultInstance();
        }
      }
      /**
       * <code>optional .de.velcommuta.denul.networking.protobuf.c2s.DeleteReply DeleteReply = 8;</code>
       */
      private com.google.protobuf.SingleFieldBuilder<
          de.velcommuta.denul.networking.protobuf.c2s.C2S.DeleteReply, de.velcommuta.denul.networking.protobuf.c2s.C2S.DeleteReply.Builder, de.velcommuta.denul.networking.protobuf.c2s.C2S.DeleteReplyOrBuilder> 
          getDeleteReplyFieldBuilder() {
        if (deleteReplyBuilder_ == null) {
          if (!(messageCase_ == 8)) {
            message_ = de.velcommuta.denul.networking.protobuf.c2s.C2S.DeleteReply.getDefaultInstance();
          }
          deleteReplyBuilder_ = new com.google.protobuf.SingleFieldBuilder<
              de.velcommuta.denul.networking.protobuf.c2s.C2S.DeleteReply, de.velcommuta.denul.networking.protobuf.c2s.C2S.DeleteReply.Builder, de.velcommuta.denul.networking.protobuf.c2s.C2S.DeleteReplyOrBuilder>(
                  (de.velcommuta.denul.networking.protobuf.c2s.C2S.DeleteReply) message_,
                  getParentForChildren(),
                  isClean());
          message_ = null;
        }
        messageCase_ = 8;
        return deleteReplyBuilder_;
      }

      // @@protoc_insertion_point(builder_scope:de.velcommuta.denul.networking.protobuf.meta.Wrapper)
    }

    static {
      defaultInstance = new Wrapper(true);
      defaultInstance.initFields();
    }

    // @@protoc_insertion_point(class_scope:de.velcommuta.denul.networking.protobuf.meta.Wrapper)
  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_de_velcommuta_denul_networking_protobuf_meta_Wrapper_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_de_velcommuta_denul_networking_protobuf_meta_Wrapper_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\021metaMessage.proto\022,de.velcommuta.denul" +
      ".networking.protobuf.meta\032\tc2s.proto\"\356\004\n" +
      "\007Wrapper\022O\n\013ClientHello\030\001 \001(\01328.de.velco" +
      "mmuta.denul.networking.protobuf.c2s.Clie" +
      "ntHelloH\000\022O\n\013ServerHello\030\002 \001(\01328.de.velc" +
      "ommuta.denul.networking.protobuf.c2s.Ser" +
      "verHelloH\000\022C\n\005Store\030\003 \001(\01322.de.velcommut" +
      "a.denul.networking.protobuf.c2s.StoreH\000\022" +
      "M\n\nStoreReply\030\004 \001(\01327.de.velcommuta.denu" +
      "l.networking.protobuf.c2s.StoreReplyH\000\022?",
      "\n\003Get\030\005 \001(\01320.de.velcommuta.denul.networ" +
      "king.protobuf.c2s.GetH\000\022I\n\010GetReply\030\006 \001(" +
      "\01325.de.velcommuta.denul.networking.proto" +
      "buf.c2s.GetReplyH\000\022E\n\006Delete\030\007 \001(\01323.de." +
      "velcommuta.denul.networking.protobuf.c2s" +
      ".DeleteH\000\022O\n\013DeleteReply\030\010 \001(\01328.de.velc" +
      "ommuta.denul.networking.protobuf.c2s.Del" +
      "eteReplyH\000B\t\n\007message"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
          de.velcommuta.denul.networking.protobuf.c2s.C2S.getDescriptor(),
        }, assigner);
    internal_static_de_velcommuta_denul_networking_protobuf_meta_Wrapper_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_de_velcommuta_denul_networking_protobuf_meta_Wrapper_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_de_velcommuta_denul_networking_protobuf_meta_Wrapper_descriptor,
        new java.lang.String[] { "ClientHello", "ServerHello", "Store", "StoreReply", "Get", "GetReply", "Delete", "DeleteReply", "Message", });
    de.velcommuta.denul.networking.protobuf.c2s.C2S.getDescriptor();
  }

  // @@protoc_insertion_point(outer_class_scope)
}
